name: Deploy to Production

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        messages: ["Hola", "CodigoFacilito", "Bootcamp GitHub Actions"]

    steps:
      - name: Print mensaje
        run: echo "${{ matrix.mensaje }}"